openapi: 3.0.1
info:
  title: Choose your own adventure (CYOA)
  description: |-
    Interactive text adventures from YAML files.
    Games have different "locations" the player can enter.
  license:
    name: MIT
    url: https://mit-license.org/
  version: 1.0.0
paths:
  /adventures:
    post:
      summary: Validate an adventure.
      operationId: validateAdventure
      requestBody:
        description: validate an adventure
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Adventure'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Adventure'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Validation exception
  /adventures/basic:
    post:
      summary: Export an adventure as Commodore 64 BASIC.
      operationId: exportBasic
      requestBody:
        description: adventure to export
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Adventure'
        required: true
      responses:
        '200':
          description: Commodore 64 BASIC source file
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    Adventure:
      type: object
      properties:
        id:
          type: string
        description:
          type: string
        startLocationId:
          $ref: '#/components/schemas/LocationId'
        locations:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/Location'
      required: 
        - id
        - description
        - startLocationId
    LocationId:
      type: string
    Location:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/LocationId'
        text:
          type: string
        options:
          type: array
          items:
            $ref: '#/components/schemas/Option'
      required: 
        - id
        - text
    Option:
      type: object
      properties:
        text:
          type: string
        locationId:
          $ref: '#/components/schemas/LocationId'
      required: 
        - text
        - locationId
    ErrorResponse:
      type: object
      properties:
        errorCode:
          type: string
        locationId:
          $ref: '#/components/schemas/LocationId'
      required:
        - errorCode